/**
 * This class creates the GUI for the staff management window.
 * @author Lauren White
 * Date: 12/1/25
 * Assignment: Stage 4 Final Project, CSCI 2210 
 */
public class StaffManagementGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffManagementGUI.class.getName());

    /**
     * Creates new form StaffManagementGUI
     */
    public StaffManagementGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpNewStatus = new javax.swing.ButtonGroup();
        tabStaffManagement = new javax.swing.JTabbedPane();
        pnlViewAllSupportStaff = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAllSupportStaff = new javax.swing.JList<>();
        pnlAddNewSupportStaff = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblStaffID = new javax.swing.JLabel();
        txtStaffID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblInitialIssueType = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pnlDeleteSupportStaff = new javax.swing.JPanel();
        lblDeleteStaff = new javax.swing.JLabel();
        cmbDeleteStaff = new javax.swing.JComboBox<>();
        btnDeleteStaff = new javax.swing.JButton();
        pnlAssignIssue = new javax.swing.JPanel();
        cmbAssignStaffList = new javax.swing.JComboBox<>();
        lblSelectStaffForIssue = new javax.swing.JLabel();
        lblIssueType = new javax.swing.JLabel();
        txtIssueType = new javax.swing.JTextField();
        lblOrderID = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        btnAssignIssue = new javax.swing.JButton();
        pnlUpdateIssueStatus = new javax.swing.JPanel();
        cmbStaffMembers = new javax.swing.JComboBox<>();
        lblSelectStaffMemberForStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCurrentStatus = new javax.swing.JTextField();
        lblSelectNewStatus = new javax.swing.JLabel();
        btnGetStatus = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();
        rdoOpen = new javax.swing.JRadioButton();
        rdoInProgress = new javax.swing.JRadioButton();
        rdoResolved = new javax.swing.JRadioButton();
        rdoClosed = new javax.swing.JRadioButton();
        pnlResolveIssue = new javax.swing.JPanel();
        lblSelectStaffForResolveIssue = new javax.swing.JLabel();
        cmbSelectStaffForResolveIssue = new javax.swing.JComboBox<>();
        btnResolveIssue = new javax.swing.JButton();
        pnlViewStaffCustomerInfo = new javax.swing.JPanel();
        lblSelectStaffForCustomerInfo = new javax.swing.JLabel();
        cmbSelectStaffForCustomerInfo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOrderInfo = new javax.swing.JTextArea();
        lblOrderInfo = new javax.swing.JLabel();
        btnViewCustomerInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Support Staff Management");

        tabStaffManagement.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabStaffManagement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pnlViewAllSupportStaff.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "View All Support Staff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lstAllSupportStaff.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ID, Name, Email", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAllSupportStaff);

        javax.swing.GroupLayout pnlViewAllSupportStaffLayout = new javax.swing.GroupLayout(pnlViewAllSupportStaff);
        pnlViewAllSupportStaff.setLayout(pnlViewAllSupportStaffLayout);
        pnlViewAllSupportStaffLayout.setHorizontalGroup(
            pnlViewAllSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewAllSupportStaffLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlViewAllSupportStaffLayout.setVerticalGroup(
            pnlViewAllSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewAllSupportStaffLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        tabStaffManagement.addTab("View All Support Staff", pnlViewAllSupportStaff);

        pnlAddNewSupportStaff.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Add New Support Staff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblName.setText("First and Last Name");

        lblAge.setText("Age");

        lblStaffID.setText("Staff ID");

        jButton1.setText("Add New Staff Member");

        lblEmail.setText("Email");

        lblInitialIssueType.setText("Initial Issue Type (or 'None')");

        javax.swing.GroupLayout pnlAddNewSupportStaffLayout = new javax.swing.GroupLayout(pnlAddNewSupportStaff);
        pnlAddNewSupportStaff.setLayout(pnlAddNewSupportStaffLayout);
        pnlAddNewSupportStaffLayout.setHorizontalGroup(
            pnlAddNewSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddNewSupportStaffLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(pnlAddNewSupportStaffLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlAddNewSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAddNewSupportStaffLayout.createSequentialGroup()
                        .addGroup(pnlAddNewSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAddNewSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtEmail)
                    .addComponent(jTextField1)
                    .addComponent(lblInitialIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlAddNewSupportStaffLayout.setVerticalGroup(
            pnlAddNewSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewSupportStaffLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblStaffID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddNewSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAge)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddNewSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInitialIssueType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        tabStaffManagement.addTab("Add New Support Staff", pnlAddNewSupportStaff);

        pnlDeleteSupportStaff.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Delete Support Staff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblDeleteStaff.setText("Select a staff member");

        cmbDeleteStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDeleteStaff.setText("Delete Staff Member");

        javax.swing.GroupLayout pnlDeleteSupportStaffLayout = new javax.swing.GroupLayout(pnlDeleteSupportStaff);
        pnlDeleteSupportStaff.setLayout(pnlDeleteSupportStaffLayout);
        pnlDeleteSupportStaffLayout.setHorizontalGroup(
            pnlDeleteSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteSupportStaffLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlDeleteSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeleteSupportStaffLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteStaff)
                .addContainerGap())
        );
        pnlDeleteSupportStaffLayout.setVerticalGroup(
            pnlDeleteSupportStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteSupportStaffLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblDeleteStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(btnDeleteStaff)
                .addContainerGap())
        );

        tabStaffManagement.addTab("Delete Support Staff", pnlDeleteSupportStaff);

        pnlAssignIssue.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Assign Issue to Staff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        cmbAssignStaffList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSelectStaffForIssue.setText("Select a staff member");

        lblIssueType.setText("Enter Issue type");

        lblOrderID.setText("Enter Order ID");

        btnAssignIssue.setText("Assign Issue");

        javax.swing.GroupLayout pnlAssignIssueLayout = new javax.swing.GroupLayout(pnlAssignIssue);
        pnlAssignIssue.setLayout(pnlAssignIssueLayout);
        pnlAssignIssueLayout.setHorizontalGroup(
            pnlAssignIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssignIssueLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlAssignIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbAssignStaffList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSelectStaffForIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlAssignIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAssignIssueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignIssue)
                .addContainerGap())
        );
        pnlAssignIssueLayout.setVerticalGroup(
            pnlAssignIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssignIssueLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlAssignIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectStaffForIssue)
                    .addComponent(lblIssueType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAssignIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAssignStaffList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOrderID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(btnAssignIssue)
                .addContainerGap())
        );

        tabStaffManagement.addTab("Assign Issue to Staff", pnlAssignIssue);

        pnlUpdateIssueStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Update Issue Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        cmbStaffMembers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSelectStaffMemberForStatus.setText("Select a staff member");

        jLabel2.setText("Current Status");

        txtCurrentStatus.setEditable(false);
        txtCurrentStatus.setCaretColor(new java.awt.Color(255, 255, 255));

        lblSelectNewStatus.setText("Select New Status");

        btnGetStatus.setText("Get Current Status");

        btnUpdateStatus.setText("Update Status");

        btnGrpNewStatus.add(rdoOpen);
        rdoOpen.setText("Open");

        btnGrpNewStatus.add(rdoInProgress);
        rdoInProgress.setText("In Progress");

        btnGrpNewStatus.add(rdoResolved);
        rdoResolved.setText("Resolved");

        btnGrpNewStatus.add(rdoClosed);
        rdoClosed.setText("Closed");

        javax.swing.GroupLayout pnlUpdateIssueStatusLayout = new javax.swing.GroupLayout(pnlUpdateIssueStatus);
        pnlUpdateIssueStatus.setLayout(pnlUpdateIssueStatusLayout);
        pnlUpdateIssueStatusLayout.setHorizontalGroup(
            pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateIssueStatusLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateIssueStatusLayout.createSequentialGroup()
                        .addGroup(pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStaffMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSelectStaffMemberForStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCurrentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdateIssueStatusLayout.createSequentialGroup()
                        .addGroup(pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectNewStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlUpdateIssueStatusLayout.createSequentialGroup()
                                .addComponent(rdoOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addGap(173, 173, 173))
                    .addGroup(pnlUpdateIssueStatusLayout.createSequentialGroup()
                        .addGroup(pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoClosed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoResolved, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoInProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdateIssueStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateStatus)
                .addGap(12, 12, 12))
        );
        pnlUpdateIssueStatusLayout.setVerticalGroup(
            pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateIssueStatusLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectStaffMemberForStatus)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStaffMembers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSelectNewStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoInProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoResolved)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoClosed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(pnlUpdateIssueStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGetStatus)
                    .addComponent(btnUpdateStatus))
                .addContainerGap())
        );

        tabStaffManagement.addTab("Update Issue Status", pnlUpdateIssueStatus);

        pnlResolveIssue.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Resolve Issue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblSelectStaffForResolveIssue.setText("Select staff member");

        cmbSelectStaffForResolveIssue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnResolveIssue.setText("Resolve Issue");

        javax.swing.GroupLayout pnlResolveIssueLayout = new javax.swing.GroupLayout(pnlResolveIssue);
        pnlResolveIssue.setLayout(pnlResolveIssueLayout);
        pnlResolveIssueLayout.setHorizontalGroup(
            pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSelectStaffForResolveIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(cmbSelectStaffForResolveIssue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResolveIssueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnResolveIssue)
                .addContainerGap())
        );
        pnlResolveIssueLayout.setVerticalGroup(
            pnlResolveIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResolveIssueLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblSelectStaffForResolveIssue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSelectStaffForResolveIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(btnResolveIssue)
                .addContainerGap())
        );

        tabStaffManagement.addTab("Resolve Issue", pnlResolveIssue);

        pnlViewStaffCustomerInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "View Staff Customer Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblSelectStaffForCustomerInfo.setText("Select a staff member");

        cmbSelectStaffForCustomerInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtOrderInfo.setEditable(false);
        txtOrderInfo.setColumns(20);
        txtOrderInfo.setRows(5);
        txtOrderInfo.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txtOrderInfo);

        lblOrderInfo.setText("Customer/Order Information");

        btnViewCustomerInfo.setText("View Customer Info");

        javax.swing.GroupLayout pnlViewStaffCustomerInfoLayout = new javax.swing.GroupLayout(pnlViewStaffCustomerInfo);
        pnlViewStaffCustomerInfo.setLayout(pnlViewStaffCustomerInfoLayout);
        pnlViewStaffCustomerInfoLayout.setHorizontalGroup(
            pnlViewStaffCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewStaffCustomerInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlViewStaffCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlViewStaffCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbSelectStaffForCustomerInfo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSelectStaffForCustomerInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewStaffCustomerInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewCustomerInfo)
                .addContainerGap())
        );
        pnlViewStaffCustomerInfoLayout.setVerticalGroup(
            pnlViewStaffCustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewStaffCustomerInfoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblSelectStaffForCustomerInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSelectStaffForCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblOrderInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewCustomerInfo)
                .addContainerGap())
        );

        tabStaffManagement.addTab("View Staff Customer Info", pnlViewStaffCustomerInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabStaffManagement)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabStaffManagement)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffManagementGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignIssue;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnGetStatus;
    private javax.swing.ButtonGroup btnGrpNewStatus;
    private javax.swing.JButton btnResolveIssue;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JButton btnViewCustomerInfo;
    private javax.swing.JComboBox<String> cmbAssignStaffList;
    private javax.swing.JComboBox<String> cmbDeleteStaff;
    private javax.swing.JComboBox<String> cmbSelectStaffForCustomerInfo;
    private javax.swing.JComboBox<String> cmbSelectStaffForResolveIssue;
    private javax.swing.JComboBox<String> cmbStaffMembers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDeleteStaff;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblInitialIssueType;
    private javax.swing.JLabel lblIssueType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderInfo;
    private javax.swing.JLabel lblSelectNewStatus;
    private javax.swing.JLabel lblSelectStaffForCustomerInfo;
    private javax.swing.JLabel lblSelectStaffForIssue;
    private javax.swing.JLabel lblSelectStaffForResolveIssue;
    private javax.swing.JLabel lblSelectStaffMemberForStatus;
    private javax.swing.JLabel lblStaffID;
    private javax.swing.JList<String> lstAllSupportStaff;
    private javax.swing.JPanel pnlAddNewSupportStaff;
    private javax.swing.JPanel pnlAssignIssue;
    private javax.swing.JPanel pnlDeleteSupportStaff;
    private javax.swing.JPanel pnlResolveIssue;
    private javax.swing.JPanel pnlUpdateIssueStatus;
    private javax.swing.JPanel pnlViewAllSupportStaff;
    private javax.swing.JPanel pnlViewStaffCustomerInfo;
    private javax.swing.JRadioButton rdoClosed;
    private javax.swing.JRadioButton rdoInProgress;
    private javax.swing.JRadioButton rdoOpen;
    private javax.swing.JRadioButton rdoResolved;
    private javax.swing.JTabbedPane tabStaffManagement;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCurrentStatus;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIssueType;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextArea txtOrderInfo;
    private javax.swing.JTextField txtStaffID;
    // End of variables declaration//GEN-END:variables
}
